# Generated by Django 4.0.3 on 2022-08-11 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeVO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('employee_number', models.IntegerField()),
                ('worked_hours', models.DecimalField(decimal_places=2, max_digits=11)),
                ('hourly_rate', models.IntegerField()),
                ('commission', models.DecimalField(decimal_places=2, max_digits=11, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SaleVO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('automobile_cost', models.DecimalField(decimal_places=2, max_digits=11)),
                ('employee_number', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=11)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceAppointmentVO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=2)),
                ('employee_number', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('cost_of_parts', models.DecimalField(decimal_places=2, max_digits=11)),
            ],
        ),
        migrations.CreateModel(
            name='PayCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_worked', models.DecimalField(decimal_places=2, max_digits=11)),
                ('total', models.DecimalField(decimal_places=2, max_digits=11)),
                ('employee_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pay_check', to='finances_rest.employeevo')),
            ],
        ),
    ]
