# Generated by Django 4.0.3 on 2022-08-11 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0005_customervo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicianVO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hourly_rate', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('employee_number', models.IntegerField(unique=True)),
                ('worked_hours', models.DecimalField(decimal_places=2, max_digits=11)),
            ],
        ),
    ]
